language: python

python:
- 2.7.12

sudo: required

services:
- mysql
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_b0f4306df9e2_key -iv $encrypted_b0f4306df9e2_iv -in deploy.enc -out deploy -d
- mkdir mysql_build
- cd mysql_build
- curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/docker/dockerfiles/mysql/init.sql
- curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/docker/dockerfiles/mysql/Dockerfile
- docker build -t egc/mysql .
- docker network create --subnet=172.18.0.0/16 dev
- docker run -d --network=dev --ip=172.18.2.2 -e MYSQL_ROOT_PASSWORD=nothing egc/mysql
- cd ..
#- mysql -e 'DROP DATABASE IF EXISTS almacenamiento'
- mysql -e 'CREATE DATABASE IF NOT EXISTS almacenamiento;'
- mysql -uroot --default-character-set=utf8 almacenamiento < almacenamiento-votos.sql
- mysql -uroot --default-character-set=utf8 almacenamiento < datos-prueba.sql

before_deploy:
  - chmod 600 deploy && mv deploy ~/.ssh/id_rsa
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/tools/deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ssh -o StrictHostKeyChecking=no deploy@egc.duckdns.org 'bash -s' < deploy.sh almacen_votos # INSERTAR NOMBRE DEL SUBSISTEMA ESPECIFICADO EN LA WIKI SIN LOS CARACTERES "< >"
  on:
    branch: master

install:
- pip install -r requirements.txt

#before_script:
#- python main.py

script:
#- python main.py &
- python pruebas.py
